[package]
name = "rocket-pokeapi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
pokeapi_getters = "0.2.1"
pokeapi_types = "0.1.4"
